version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: chinelink
        container_name: chinelink
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www
            - ./php.ini:/usr/local/etc/php/php.ini
        networks:
            - laravel

    webserver:
        image: nginx:alpine
        container_name: nginx_chinelink
        restart: unless-stopped
        ports:
            - "81:80"
            - "444:443"
        volumes:
            - .:/var/www
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
            - /etc/letsencrypt:/etc/letsencrypt
        networks:
            - laravel

    db:
        image: mariadb:latest
        container_name: mariadb_chinelink
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: laravel
        ports:
            - "3308:3306"
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - laravel

networks:
    laravel:

volumes:
    dbdata:
