version: '3.8'

services:
    nginx:
        image: nginx:latest
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./default.conf:/etc/nginx/conf.d/default.conf:ro
            - /etc/letsencrypt:/etc/letsencrypt:ro
            - .:/var/www
        depends_on:
            - php
        networks:
            - chinelink

    php:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/var/www
        networks:
            - chinelink

    db:
        image: mariadb:latest
        container_name: mariadb
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: chinelink
            MYSQL_USER: chinelink
            MYSQL_PASSWORD: chinelink
        ports:
            - "3307:3306"
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - chinelink

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - 8080:80
        links:
            - db
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
            PMA_ABSOLUTE_URI: https://chine.nigerdev.com/phpmyadmin
        volumes:
            - .docker/phpmyadmin/sessions:/sessions

networks:
    chinelink:

volumes:
    dbdata:
