version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_app
    environment:
      - DATABASE_URL=mysql://laravel:secret@db:3306/laravel
    volumes:
      - .:/var/www/chinelink
    networks:
      - symfony

  web:
    image: nginx:latest
    container_name: nginx_web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/var/www/chinelink
      - ./nginx/conf.d:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - symfony
    depends_on:
      - app

  db:
    image: mariadb:latest
    container_name: mariadb_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - symfony
  artisan:
    build:
      context: .
    command: bash -c "composer install"
    volumes:
      - .:/var/www/chinelink
    depends_on:
      - db
    networks:
      - laravel
volumes:
  db_data:

networks:
  symfony:
    driver: bridge
