version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: chinelink
        container_name: chinelink_app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www
            - ./php.ini:/usr/local/etc/php/conf.d/php.ini
        networks:
            - chinelink

    webserver:
        image: nginx:alpine
        container_name: nginx_chinelink
        restart: unless-stopped
        ports:
            - "8082:80"
            - "8445:443"
        volumes:
            - .:/var/www
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
            - /etc/letsencrypt:/etc/letsencrypt
        networks:
            - chinelink

    db:
        image: mariadb:latest
        container_name: mariadb_chinelink
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: chinelink
            MYSQL_USER: chinelink
            MYSQL_PASSWORD: chinelink
        ports:
            - "3309:3306"
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - chinelink

networks:
    chinelink:

volumes:
    dbdata:
